#(comando)(dispositivo)[(numero de dispositivo)(area)|(area)|(numero de dispositivo)]
REGEXCOMMANDS = "^\s*((\w+)\s(\w+)(\s(\w+)\s(\w+)|\s(\w+))?).*$"
TOKEN = "232824243:AAGNAqLPieu5SN92PTjGDBzWspdRdp-Slos"
TELEFONO = "5491169368980"
PASSWORD = "hpbIJQnR4DlrQYoQPOI1p7Av56w="

#variables >
DISP_LUCES = "luces"
DISP_LUZ = "luz"
DISP_ALARMA = "alarma"
DISP_SENSOR = "sensor"
DISP_VENTILADOR = "ventilador"
DISP_INEXISTENTES = "Dispositivo inexistente"
DISP_ON = "Dispositivo encendido"
DISP_OFF = "Dispositivo apagado"
DISP_ON_PLUS = "Dispositivos encendidos"
DISP_OFF_PLUS = "Dispositivos apagados"
DISP_ACTIVADO_ALARMA = "Alarma activada"
DISP_DESACTIVADO_ALARMA = "Alarma desactivado"
DISP_ALARMA_DETECTAR = "Intruso detectado"
DISP_HUMEDAD = "humedad"
DISP_TEMPERATURA = "temperatura"
COMMAND_ENCENDER = "enceder"
COMMAND_APAGAR = "apagar"
COMMAND_ACTIVAR = "activar"
COMMAND_APAGAR = "desactivar"
COMMAND_INVALID = "comando invalido"
COMMAND_UNRECOGNIZABLE = "No se reconoce el comando"
COMMAND_STATES = "estado"
 
