# -*- coding: utf-8 -*-
#(comando)(dispositivo)[(numero de dispositivo)(area)|(area)|(numero de dispositivo)]
REGEXCOMMANDS = "^\s*((\w+)\s(\w+)(\s(\w+)\s(\w+)|\s(\w+))?).*$"
TOKEN = "232824243:AAGNAqLPieu5SN92PTjGDBzWspdRdp-Slos"
TELEFONO = "5491169368980"
PASSWORD = "hpbIJQnR4DlrQYoQPOI1p7Av56w="

#variables >
DISP_LUCES = "luces"
DISP_LUZ = "luz"
DISP_ALARMA = "alarma"
DISP_SENSOR = "sensor"
DISP_VENTILADOR = "ventilador"
DISP_INEXISTENTES = "Dispositivo inexistente"
DISP_ON = "Dispositivo encendido"
DISP_OFF = "Dispositivo apagado"
DISP_ON_PLUS = "Dispositivos encendidos"
DISP_OFF_PLUS = "Dispositivos apagados"
DISP_ACTIVADO_ALARMA = "Alarma activada"
DISP_DESACTIVADO_ALARMA = "Alarma desactivado"
DISP_ALARMA_DETECTAR = "Intruso detectado"
DISP_HUMEDAD = "humedad"
DISP_TEMPERATURA = "temperatura"
COMMAND_ENCENDER = "encender"
COMMAND_APAGAR = "apagar"
COMMAND_ACTIVAR = "activar"
COMMAND_ABRIR = "abrir"
COMMAND_CERRAR = "cerrar"
COMMAND_APAGAR = "desactivar"
COMMAND_INVALID = "Comando inválido"
COMMAND_UNRECOGNIZABLE = "No se reconoce el comando"
COMMAND_STATES = "estado"
ERROR_USUARIO_NO_REGISTRADO = "El teléfono no se encuentra configurado en el sistema, por favor configúrelo para poder utilizar HomeBerry"
ERROR_USUARIO_RESTRINGIDO = "Tenés un perfil restringido para realizar esta acción"
MONOGO_TELEFONO = "telefono"
MONOGO_ZONA = "zona"
MONOGO_TIPO = "tipo"
MONOGO_NOMBRE = "nombre"
MONOGO_TARJETA_COORDENADAS = "tc" 
MAIL_USERNAME = "homeberry.ar"
MAIL_PASSWORD = "proyecto2016"
MAIL = "homeberry.ar@gmail.com"

